# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import customer_db_pb2 as customer__db__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in customer_db_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomerDatabaseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSeller = channel.unary_unary(
                '/customer_db.CustomerDatabase/CreateSeller',
                request_serializer=customer__db__pb2.CreateSellerRequest.SerializeToString,
                response_deserializer=customer__db__pb2.CreateSellerResponse.FromString,
                _registered_method=True)
        self.CreateBuyer = channel.unary_unary(
                '/customer_db.CustomerDatabase/CreateBuyer',
                request_serializer=customer__db__pb2.CreateBuyerRequest.SerializeToString,
                response_deserializer=customer__db__pb2.CreateBuyerResponse.FromString,
                _registered_method=True)
        self.GetSellerByName = channel.unary_unary(
                '/customer_db.CustomerDatabase/GetSellerByName',
                request_serializer=customer__db__pb2.GetSellerByNameRequest.SerializeToString,
                response_deserializer=customer__db__pb2.SellerResponse.FromString,
                _registered_method=True)
        self.GetBuyerByName = channel.unary_unary(
                '/customer_db.CustomerDatabase/GetBuyerByName',
                request_serializer=customer__db__pb2.GetBuyerByNameRequest.SerializeToString,
                response_deserializer=customer__db__pb2.BuyerResponse.FromString,
                _registered_method=True)
        self.GetSeller = channel.unary_unary(
                '/customer_db.CustomerDatabase/GetSeller',
                request_serializer=customer__db__pb2.GetSellerRequest.SerializeToString,
                response_deserializer=customer__db__pb2.SellerResponse.FromString,
                _registered_method=True)
        self.UpdateSeller = channel.unary_unary(
                '/customer_db.CustomerDatabase/UpdateSeller',
                request_serializer=customer__db__pb2.UpdateSellerRequest.SerializeToString,
                response_deserializer=customer__db__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.GetBuyer = channel.unary_unary(
                '/customer_db.CustomerDatabase/GetBuyer',
                request_serializer=customer__db__pb2.GetBuyerRequest.SerializeToString,
                response_deserializer=customer__db__pb2.BuyerResponse.FromString,
                _registered_method=True)
        self.UpdateBuyer = channel.unary_unary(
                '/customer_db.CustomerDatabase/UpdateBuyer',
                request_serializer=customer__db__pb2.UpdateBuyerRequest.SerializeToString,
                response_deserializer=customer__db__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/customer_db.CustomerDatabase/CreateSession',
                request_serializer=customer__db__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/customer_db.CustomerDatabase/GetSession',
                request_serializer=customer__db__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/customer_db.CustomerDatabase/DeleteSession',
                request_serializer=customer__db__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.ResetAll = channel.unary_unary(
                '/customer_db.CustomerDatabase/ResetAll',
                request_serializer=customer__db__pb2.ResetRequest.SerializeToString,
                response_deserializer=customer__db__pb2.GenericResponse.FromString,
                _registered_method=True)


class CustomerDatabaseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerDatabaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSeller,
                    request_deserializer=customer__db__pb2.CreateSellerRequest.FromString,
                    response_serializer=customer__db__pb2.CreateSellerResponse.SerializeToString,
            ),
            'CreateBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBuyer,
                    request_deserializer=customer__db__pb2.CreateBuyerRequest.FromString,
                    response_serializer=customer__db__pb2.CreateBuyerResponse.SerializeToString,
            ),
            'GetSellerByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerByName,
                    request_deserializer=customer__db__pb2.GetSellerByNameRequest.FromString,
                    response_serializer=customer__db__pb2.SellerResponse.SerializeToString,
            ),
            'GetBuyerByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerByName,
                    request_deserializer=customer__db__pb2.GetBuyerByNameRequest.FromString,
                    response_serializer=customer__db__pb2.BuyerResponse.SerializeToString,
            ),
            'GetSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeller,
                    request_deserializer=customer__db__pb2.GetSellerRequest.FromString,
                    response_serializer=customer__db__pb2.SellerResponse.SerializeToString,
            ),
            'UpdateSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSeller,
                    request_deserializer=customer__db__pb2.UpdateSellerRequest.FromString,
                    response_serializer=customer__db__pb2.GenericResponse.SerializeToString,
            ),
            'GetBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyer,
                    request_deserializer=customer__db__pb2.GetBuyerRequest.FromString,
                    response_serializer=customer__db__pb2.BuyerResponse.SerializeToString,
            ),
            'UpdateBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBuyer,
                    request_deserializer=customer__db__pb2.UpdateBuyerRequest.FromString,
                    response_serializer=customer__db__pb2.GenericResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=customer__db__pb2.CreateSessionRequest.FromString,
                    response_serializer=customer__db__pb2.CreateSessionResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=customer__db__pb2.GetSessionRequest.FromString,
                    response_serializer=customer__db__pb2.SessionResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=customer__db__pb2.DeleteSessionRequest.FromString,
                    response_serializer=customer__db__pb2.GenericResponse.SerializeToString,
            ),
            'ResetAll': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetAll,
                    request_deserializer=customer__db__pb2.ResetRequest.FromString,
                    response_serializer=customer__db__pb2.GenericResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'customer_db.CustomerDatabase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('customer_db.CustomerDatabase', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerDatabase(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer_db.CustomerDatabase/CreateSeller',
            customer__db__pb2.CreateSellerRequest.SerializeToString,
            customer__db__pb2.CreateSellerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer_db.CustomerDatabase/CreateBuyer',
            customer__db__pb2.CreateBuyerRequest.SerializeToString,
            customer__db__pb2.CreateBuyerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer_db.CustomerDatabase/GetSellerByName',
            customer__db__pb2.GetSellerByNameRequest.SerializeToString,
            customer__db__pb2.SellerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyerByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer_db.CustomerDatabase/GetBuyerByName',
            customer__db__pb2.GetBuyerByNameRequest.SerializeToString,
            customer__db__pb2.BuyerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer_db.CustomerDatabase/GetSeller',
            customer__db__pb2.GetSellerRequest.SerializeToString,
            customer__db__pb2.SellerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer_db.CustomerDatabase/UpdateSeller',
            customer__db__pb2.UpdateSellerRequest.SerializeToString,
            customer__db__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer_db.CustomerDatabase/GetBuyer',
            customer__db__pb2.GetBuyerRequest.SerializeToString,
            customer__db__pb2.BuyerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer_db.CustomerDatabase/UpdateBuyer',
            customer__db__pb2.UpdateBuyerRequest.SerializeToString,
            customer__db__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer_db.CustomerDatabase/CreateSession',
            customer__db__pb2.CreateSessionRequest.SerializeToString,
            customer__db__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer_db.CustomerDatabase/GetSession',
            customer__db__pb2.GetSessionRequest.SerializeToString,
            customer__db__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer_db.CustomerDatabase/DeleteSession',
            customer__db__pb2.DeleteSessionRequest.SerializeToString,
            customer__db__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer_db.CustomerDatabase/ResetAll',
            customer__db__pb2.ResetRequest.SerializeToString,
            customer__db__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
